version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

    # ✅ Enforce resource limits
    mem_limit: 1g
    cpus: 2.0

    # ✅ Optional: safer health check
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f chromium || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3